const data = `
haschar(advertise, advertise).
hasspec(advertise, marksmanship).
haschar(advertise, tiref).
hasspec(tiref, fire).
haschar(advertise, notadvertise).
hasspec(notadvertise, feraldps).
haschar(advertise, progression).
hasspec(progression, affliction).
haschar(advertise, irone).
hasspec(irone, combat).
haschar(alitta, alitadisc).
hasspec(alitadisc, discipline).
haschar(alitta, alitta).
hasspec(alitta, combat).
haschar(alitta, alittad).
hasspec(alittad, discipline).
haschar(alitta, cahlan).
hasspec(cahlan, bloodtank).
haschar(alitta, invuctus).
hasspec(invuctus, discipline).
haschar(alitta, layoa).
hasspec(layoa, discipline).
haschar(alitta, femalewarr).
hasspec(femalewarr, fury).
haschar(alitta, todesengele).
hasspec(todesengele, bloodtank).
haschar(alitta, cosmicheals).
hasspec(cosmicheals, holy).
haschar(aramid, aramid).
hasspec(aramid, combat).
haschar(aramid, carbotech).
hasspec(carbotech, retribution).
hasspec(carbotech, protection).
haschar(asheria, asheria).
hasspec(asheria, balance).
hasspec(asheria, feraltank).
haschar(asheria, notasheria).
hasspec(notasheria, balance).
hasspec(notasheria, restodruid).
haschar(asheria, airehsa).
hasspec(airehsa, balance).
haschar(asheria, asherian).
hasspec(asherian, balance).
hasspec(asherian, feraltank).
haschar(asheria, notasheria).
hasspec(notasheria, balance).
hasspec(notasheria, restodruid).
haschar(beli, beli).
hasspec(beli, retribution).
hasspec(beli, protection).
haschar(beli, belka).
hasspec(belka, feraltank).
haschar(beli, belliarr).
hasspec(belliarr, combat).
haschar(beli, bllink).
hasspec(bllink, shadow).
haschar(beli, crni).
hasspec(crni, fury).
haschar(beli, whitemagi).
hasspec(whitemagi, fire).
haschar(beli, whiteman).
hasspec(whiteman, unholydps).
haschar(beli, whitemann).
hasspec(whitemann, frostdps).
haschar(asiimar, asiimar).
hasspec(asiimar, marksmanship).
haschar(asiimar, asiimer).
hasspec(asiimer, balance).
hasspec(asiimer, restodruid).
haschar(asiimar, burstmachine).
hasspec(burstmachine, fury).
haschar(asiimar, plagemachine).
hasspec(plagemachine, unholydps).
haschar(asiimar, catchmebaby).
hasspec(catchmebaby, combat).
haschar(asiimar, ikissedagirl).
hasspec(ikissedagirl, holy).
haschar(budey, budey).
hasspec(budey, restodruid).
hasspec(budey, balance).
haschar(budey, elorria).
hasspec(elorria, fire).
haschar(budey, avrosia).
hasspec(avrosia, holy).
haschar(budey, warmfate).
hasspec(warmfate, discipline).
hasspec(warmfate, shadow).
haschar(budey, strify).
hasspec(strify, marksmanship).
haschar(budey, obi).
hasspec(obi, holy).
hasspec(obi, protection).
haschar(budey, buddie).
hasspec(buddie, restodruid).
haschar(bunnylover, bunnyhater).
hasspec(bunnyhater, holy).
haschar(bunnylover, bunnylover).
hasspec(bunnylover, holypriest).
hasspec(bunnylover, discipline).
haschar(bunnylover, muffinhater).
hasspec(muffinhater, restodruid).
haschar(bunnylover, muffinlover).
hasspec(muffinlover, restoration).
haschar(calbo, arbol).
hasspec(arbol, restodruid).
haschar(calbo, calbito).
hasspec(calbito, demonology).
hasspec(calbito, affliction).
haschar(calbo, calbo).
hasspec(calbo, discipline).
hasspec(calbo, shadow).
haschar(calbo, elcalbo).
hasspec(elcalbo, holy).
hasspec(elcalbo, retribution).
haschar(calbo, elmuerte).
hasspec(elmuerte, frostdps).
hasspec(elmuerte, bloodtank).
haschar(calbo, eltotem).
hasspec(eltotem, restoration).
haschar(calbo, livingbombs).
hasspec(livingbombs, fire).
haschar(calbo, platehealer).
hasspec(platehealer, holy).
haschar(calbo, karrier).
hasspec(karrier, fury).
haschar(carrykk, geydar).
hasspec(geydar, unholydps).
hasspec(geydar, frostdps).
haschar(carrykk, carrykk).
hasspec(carrykk, fury).
haschar(carrykk, goolen).
hasspec(goolen, retribution).
hasspec(goolen, holy).
haschar(carrykk, ikita).
hasspec(ikita, shadow).
hasspec(ikita, discipline).
haschar(carrykk, phylaa).
hasspec(phylaa, restoration).
hasspec(phylaa, enhancement).
haschar(carrykk, thoga).
hasspec(thoga, combat).
haschar(carrykk, ozail).
hasspec(ozail, fire).
haschar(chillness, chillness).
hasspec(chillness, shadow).
hasspec(chillness, discipline).
haschar(chillness, chillrip).
hasspec(chillrip, restoration).
haschar(chillness, chillfaith).
hasspec(chillfaith, shadow).
haschar(chillness, jeandarc).
hasspec(jeandarc, retribution).
hasspec(jeandarc, holy).
haschar(chillness, corruptchill).
hasspec(corruptchill, demonology).
haschar(chillness, illfaith).
hasspec(illfaith, discipline).
hasspec(illfaith, holypriest).
haschar(chillness, saintsinner).
hasspec(saintsinner, affliction).
hasspec(saintsinner, demonology).
haschar(cowardy, acolyte).
hasspec(acolyte, shadow).
haschar(cowardy, tolsty).
hasspec(tolsty, feraltank).
haschar(cowardy, cowardy).
hasspec(cowardy, combat).
haschar(cowardy, felore).
hasspec(felore, demonology).
haschar(cowardy, karisma).
hasspec(karisma, fire).
haschar(cowardy, necropsy).
hasspec(necropsy, unholydps).
haschar(cowardy, anni).
hasspec(anni, marksmanship).
haschar(dagraamis, dagraamis).
hasspec(dagraamis, restodruid).
haschar(dagraamis, azerase).
hasspec(azerase, holypriest).
haschar(dagraamis, dagrouge).
hasspec(dagrouge, combat).
haschar(dagraamis, dagnab).
hasspec(dagnab, demonology).
haschar(dedoviya, dedoviya).
hasspec(dedoviya, fire).
haschar(dedoviya, nebezao).
hasspec(nebezao, combat).
haschar(dedoviya, slipknoter).
hasspec(slipknoter, fury).
haschar(ducksy, quackscope).
hasspec(quackscope, marksmanship).
haschar(ducksy, ducksy).
hasspec(ducksy, balance).
hasspec(ducksy, feraltank).
haschar(ducksy, ducksaya).
hasspec(ducksaya, restodruid).
haschar(ducksy, quacksy).
hasspec(quacksy, shadow).
hasspec(quacksy, discipline).
haschar(ducksy, quackzini).
hasspec(quackzini, demonology).
haschar(ducksy, donaldquack).
hasspec(donaldquack, feraldps).
haschar(ducksy, lolmotov).
hasspec(lolmotov, balance).
haschar(ducksy, quakegodx).
hasspec(quakegodx, shadow).
haschar(ducksy, discogodx).
hasspec(discogodx, discipline).
haschar(ducksy, duckfest).
hasspec(duckfest, balance).
haschar(ducksy, ducks).
hasspec(ducks, shadow).
haschar(duleantic, duleantic).
hasspec(duleantic, retribution).
hasspec(duleantic, protection).
haschar(duleantic, kassapin).
hasspec(kassapin, combat).
haschar(duleantic, plavusha).
hasspec(plavusha, demonology).
haschar(duleantic, veryfatdk).
hasspec(veryfatdk, unholydps).
hasspec(veryfatdk, bloodtank).
haschar(duleantic, miilivoje).
hasspec(miilivoje, fire).
haschar(dzaja, dzaja).
hasspec(dzaja, protection).
haschar(ejk, ejk).
hasspec(ejk, restoration).
hasspec(ejk, elemental).
haschar(ejk, dnz).
hasspec(dnz, fury).
haschar(ejk, flowk).
hasspec(flowk, retribution).
hasspec(flowk, holy).
haschar(ejk, umiti).
hasspec(umiti, restodruid).
haschar(ejk, sfantatreime).
hasspec(sfantatreime, shadow).
haschar(ejk, milies).
hasspec(milies, fire).
haschar(ejk, onycs).
hasspec(onycs, frostdps).
hasspec(onycs, bloodtank).
haschar(elaiss, annebell).
hasspec(annebell, discipline).
hasspec(annebell, shadow).
haschar(elaiss, creampies).
hasspec(creampies, combat).
haschar(elaiss, elaiss).
hasspec(elaiss, feraltank).
haschar(elaiss, puffylips).
hasspec(puffylips, restoration).
hasspec(puffylips, enhancement).
haschar(facetheboy, afner).
hasspec(afner, bloodtank).
haschar(facetheboy, dayslut).
hasspec(dayslut, protection).
hasspec(dayslut, holy).
haschar(facetheboy, facetheboy).
hasspec(facetheboy, marksmanship).
haschar(facetheboy, nightslut).
hasspec(nightslut, feraltank).
hasspec(nightslut, balance).
haschar(felmaiden, felmaiden).
hasspec(felmaiden, demonology).
haschar(felmaiden, naturalpiper).
hasspec(naturalpiper, balance).
haschar(felmaiden, radiantsteel).
hasspec(radiantsteel, protection).
haschar(felmaiden, sorrowbane).
hasspec(sorrowbane, bloodtank).
haschar(florynelsham, florynelsham).
hasspec(florynelsham, restoration).
haschar(florynelsham, florynel).
hasspec(florynel, retribution).
hasspec(florynel, holy).
haschar(florynelsham, quenlethal).
hasspec(quenlethal, marksmanship).
haschar(florynelsham, lethallady).
hasspec(lethallady, fire).
hasspec(lethallady, arcane).
haschar(florynelsham, holythunder).
hasspec(holythunder, fury).
haschar(florynelsham, lethallock).
hasspec(lethallock, demonology).
haschar(florynelsham, kalyda).
hasspec(kalyda, retribution).
haschar(florynelsham, loveisblind).
hasspec(loveisblind, discipline).
hasspec(loveisblind, shadow).
haschar(florynelsham, floryneldk).
hasspec(floryneldk, unholydps).
haschar(florynelsham, lovelybeast).
hasspec(lovelybeast, restodruid).
haschar(flybyflys, dontknow).
hasspec(dontknow, discipline).
haschar(flybyflys, doomteller).
hasspec(doomteller, restoration).
haschar(flybyflys, flybyflys).
hasspec(flybyflys, fire).
haschar(flybyflys, healingmate).
hasspec(healingmate, balance).
hasspec(healingmate, restodruid).
haschar(flybyflys, musiqq).
hasspec(musiqq, holy).
hasspec(musiqq, protection).
haschar(flybyflys, summonportal).
hasspec(summonportal, demonology).
haschar(flybyflys, whatisdis).
hasspec(whatisdis, marksmanship).
haschar(flybyflys, bagaina).
hasspec(bagaina, retribution).
hasspec(bagaina, holy).
haschar(fokit, fokit).
hasspec(fokit, shadow).
hasspec(fokit, discipline).
haschar(fokit, lokit).
hasspec(lokit, marksmanship).
haschar(fokit, sokit).
hasspec(sokit, fury).
haschar(fu, fu).
hasspec(fu, combat).
haschar(fu, magdalene).
hasspec(magdalene, demonology).
hasspec(magdalene, affliction).
haschar(fu, ayy).
hasspec(ayy, balance).
hasspec(ayy, restodruid).
haschar(fu, milkyway).
hasspec(milkyway, shadow).
hasspec(milkyway, discipline).
haschar(fu, bitter).
hasspec(bitter, feraldps).
hasspec(bitter, feraltank).
haschar(fu, probably).
hasspec(probably, holy).
hasspec(probably, protection).
haschar(fu, car).
hasspec(car, protection).
hasspec(car, holy).
slotis(slot0, bloodtank).
slotis(slot0, feraltank).
slotis(slot1, protection).
slotis(slot2, holy).
slotis(slot3, restoration).
slotis(slot4, discipline).
slotis(slot5, frostdps).
slotis(slot5, feraldps).
slotis(slot5, enhancement).
slotis(slot6, unholydps).
slotis(slot7, retribution).
slotis(slot8, retribution).
slotis(slot9, combat).
slotis(slot10, combat).
slotis(slot11, fury).
slotis(slot12, fury).
slotis(slot13, fury).
slotis(slot14, balance).
slotis(slot14, fire).
slotis(slot15, shadow).
slotis(slot16, shadow).
slotis(slot17, marksmanship).
slotis(slot18, marksmanship).
slotis(slot19, demonology).
slotis(slot20, balance).
slotis(slot21, fire).
slotis(slot21, affliction).
slotis(slot22, fire).
slotis(slot22, affliction).
slotis(slot23, fire).
slotis(slot24, fire).

get_comp :-
    slotis(slot1, SPEC1), 
    hasspec(CHAR1, SPEC1), 
    haschar(PLAYER1, CHAR1), 
    slotis(slot2, SPEC2), 
    hasspec(CHAR2, SPEC2), 
    haschar(PLAYER2, CHAR2), 
    slotis(slot3, SPEC3), 
    hasspec(CHAR3, SPEC3), 
    haschar(PLAYER3, CHAR3),
    PLAYER1 \== PLAYER2,
    PLAYER1 \== PLAYER3,
    PLAYER2 \== PLAYER3,
    format('~w (~w): ~w ~n', [CHAR1, PLAYER1, SPEC1]),
    format('~w (~w): ~w ~n', [CHAR2, PLAYER2, SPEC2]),
    format('~w (~w): ~w ~n', [CHAR3, PLAYER3, SPEC3]).
`;

module.exports = data;